### ISSUE TITLE
Compilation fails due to timekeeping

### ISSUE THREAD

**Issue by kebasaa** [philbowles/h4plugins#3]
Hi,

I've installed the libraries that are mentioned in the _Readme_ file, but compilation fails. Could you please help with it? Am I missing a library for timekeeping?

```
.\Arduino\libraries\h4plugins-master\src\H4P_Timekeeper.cpp: In member function 'uint32_t H4P_Timekeeper::__alarmCore(std::vector<std::basic_string<char> >, bool, H4BS_FN_SWITCH)':
.\Arduino\libraries\h4plugins-master\src\H4P_Timekeeper.cpp:68:71: error: 'TAG' was not declared in this scope

         },msDue,daily ? msDue:0,H4Countdown(1),nullptr,TAG(daily ? 7:3));
```

**Comment by philbowles** [comment]
Apologies for the delay and apologies for the bug - its fixed in v0.5.5 just released. I'd be very happy if you would try again - also you will get quicker responses in future [here](https://www.facebook.com/groups/h4plugins/)

**Comment by kebasaa** [comment]
Thanks, I just tested it. I'm still getting the same error.

I don't have facebook, so connecting there is a bit hard.
